apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-dep
  name: nginx-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-dep
  type: nodePort
status:
  loadBalancer: {}
